#pragma config(Motor,  port2,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++
[I/O Port]          [Name]              [Type]                							 [Description]
Motor Port 2        frontRight          VEX 393 High Speed Motor             Front Right motor
Motor Port 3        frontLeft           VEX 393 High Speed Motor             Front Left motor
Motor Port 4        backRight           VEX 393 High Speed Motor             Back Right motor
Motor Port 5        backLeft            VEX 393 High Speed Motor             Back Left motor
--------------------------------------------------------------------------------------------------*/

task main() {

	// Initialize variables for deadzone
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 15;
 
	//Loop Forever
	while(1 == 1) {
	//Create "deadzone" for Y1/Ch3
	if (abs(vexRT[Ch3]) > threshold) {
		Y1 = vexRT[Ch3];
	}
	else {
		Y1 = 0;
	}
	//Create "deadzone" for X1/Ch4
	if (abs(vexRT[Ch4]) > threshold) {
		X1 = vexRT[Ch4];
	}
	else {
		X1 = 0;
	}
	//Create "deadzone" for X2/Ch1
	if (abs(vexRT[Ch1]) > threshold) {
		X2 = vexRT[Ch1];
	}
	else {
		X2 = 0;
	}
	
	//Remote Control Commands
	motor[frontRight] = Y1 - X2 - X1;
	motor[backRight] =  Y1 - X2 + X1;
	motor[frontLeft] = Y1 + X2 + X1;
	motor[backLeft] =  Y1 + X2 - X1;
	}
}
