#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           pickup,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           track,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           shooter,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

// Written by: Omar Rahman
// East River Robotics Team 2015 - 2016

// PORT NOTES:
// Port 2: 2 Right motor
// Port 3: 2 Left motor
// Port 4: Pickup
// Port 5: Track
// Port 6: Shooter

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// Drive 24 inches
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;

	// Keep driving at 127 for 1 second
	// TODO: Need to measure how long it takes to reach 24 inches
	wait1Msec(1000);

	// Stop the Robot
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	// Turn 45 degrees
	// ESTIMATES:
	// Speed: 80 Time: 100ms Angle: 15
	motor[leftMotor] = 80;
	motor[rightMotor] = 80;

	wait1Msec(300);

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	// Drive 23.75 inches
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;

	// Keep driving at 127 for 1 second
	// TODO: Need to measure how long it takes to reach 23.75 inches
	wait1Msec(950);

	// Stop the Robot
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	// Pick up balls
	motor[pickup] = 127;
	motor[track] = 127;
	motor[shooter] = 127;
	
	wait1Msec(5000);
	
	// Reset
	motor[pickup] = 0;
	motor[track] = 0;
	motor[shooter] = 0;

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
		// Tank driving
		// Channel 3 = Left motor
		// Channel 2 = Right Motor
	
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];
		
		// Ball pickup
		// If Button 6U is pressed turn on motor[pickup]
		// Brings the ball(s) inside the robot to the tracks
		if (vexRT[Btn6U] == 1) {
			motor[pickup] = -127;
		}
		// If Button 6U isn't pressed but Button 6D turn on motor[pickup]
		// Pushes the ball(s) out of the robot (In case they get stuck)
		else if (vexRT[Btn6D] == 1) {
			motor[pickup] = 127;
		}
		// If everything else is false, turn off motor[pickup]
		else {
			motor[pickup] = 0;	
		}
		
		// Track
		// If Button 5U is pressed turn on motor[track] to 127
		// Brings the ball(s) up to the shooter
		if (vexRT[Btn5U] == 1) {
			motor[track] = 127;	
		}
		// If Button 5U isn't pressed but Button 5D is pressed turn on motor[track] to -127
		// In case a ball(s) gets stuck it will reverse the tracks
		else if (vexRT[Btn5D] == 1) {
			motor[track] = -127;	
		}
		// If everything else is false, turn off motor[track]
		else {
			motor[track] = 0;
		}
		
		// Shooter
		// If Button 8D is pressed turn on motor[shooter]
		// Shoots the ball(s) to the net
		if (vexRT[Btn8D] == 1) {
			motor[shooter] = 127;
		}
		// If Button 8D isn't pressed turn off motor[shooter]
		else {
			motor[shooter] = 0;
		}
	}
}
