#pragma config(Motor,  port1,           driveLF,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           driveRF,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           driveLB,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveRB,       tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

// Written by: Omar Rahman
// East River Robotics Team 2015 - 2016

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// Drive 24 inches
	motor[driveLF] = 127;
	motor[driveLB] = 127;
	motor[driveRF] = 127;
	motor[driveRB] = 127;

	// Keep driving at 127 for 1 second
	// TODO: Need to measure how long it takes to reach 24 inches
	wait1Msec(1000);

	// Stop the Robot
	motor[driveLF] = 0;
	motor[driveLB] = 0;
	motor[driveRF] = 0;
	motor[driveRB] = 0;

	// Turn 45 degrees
	// ESTIMATES:
	// Speed: 80 Time: 100ms Angle: 15
	motor[driveLF] = 80;
	motor[driveLB] = 80;
	motor[driveRF] = -80;
	motor[driveRB] = -80;

	wait1Msec(300);

	motor[driveLF] = 0;
	motor[driveLB] = 0;
	motor[driveRF] = 0;
	motor[driveRB] = 0;

	// Drive 23.75 inches
	motor[driveLF] = 127;
	motor[driveLB] = 127;
	motor[driveRF] = 127;
	motor[driveRB] = 127;

	// Keep driving at 127 for 1 second
	// TODO: Need to measure how long it takes to reach 23.75 inches
	wait1Msec(950);

	// Stop the Robot
	motor[driveLF] = 0;
	motor[driveLB] = 0;
	motor[driveRF] = 0;
	motor[driveRB] = 0;

	// TODO: Find the motor port that picks up the balls
	// Pick up balls

	// Shoot

	// Reset

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	while (true)
	{
		// Arcade driving
		// Channel 1 = Reverse and Forward
		// Channel 2 = Turning

		motor[driveLF] = vexRT[Ch2] + vexRT[Ch1];
		motor[driveLB] = vexRT[Ch2] + vexRT[Ch1];
		motor[driveRF] = vexRT[Ch2] - vexRT[Ch1];
		motor[driveRB] = vexRT[Ch2] - vexRT[Ch1];
	}
}
