#pragma config(Motor,  port2,           frontRight,    tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

	while(true) {
		motor[frontRight] = vexRT[Ch2];
		motor[frontLeft] = vexRT[Ch3];
		motor[backRight] = vexRT[Ch2];
		motor[backLeft] = vexRT[Ch3];

		if (vexRT[Btn5U] == 1) {
			motor[frontLeft] = 127;
			motor[backRight] = 127;
			motor[frontRight] = -127;
			motor[backLeft] = -127;
		}
		else if (vexRT[Btn6U] == 1) {
			motor[frontLeft] = -127;
			motor[backRight] = -127;
			motor[frontRight] = 127;
			motor[backLeft] = 127;
		}
		else {
			motor[frontLeft] = 0;
			motor[backRight] = 0;
			motor[frontRight] = 0;
			motor[backLeft] = 0;
		}
	}
}
